# Generated by Django 2.2.2 on 2019-06-15 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20190312_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='sample',
            field=models.BooleanField(default=False),
        ),
    ]
